CREATE DATABASE IF NOT EXISTS juego;
USE juego;

CREATE TABLE resultados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  tiempo INT NOT NULL,
  movimientos INT NOT NULL,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP
)
